apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gajanand
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-gajanand
  template:
    metadata:
      labels:
        app: hello-gajanand
    spec:
      containers:
      - name: hello-gajanand
        image: bhavanigajannad/hello-gajanand:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000