apiVersion: v1
kind: Service
metadata:
  name: hello-gajanand-svc
spec:
  type: NodePort
  selector:
    app: hello-gajanand
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30007
